language: node_js
node_js:
  - "lts/*"
cache:
  directories:
  - node_modules # NPM packages
install:
  - npm install -g codecov
  - npm install
script:
  - npm run build
  - npm run lint
  - npm run test
  - codecov

