backend:
  name: github
  branch: master
  repo: product-mindset/content

media_folder: static/img
public_folder: /img

collections:
  - name: page
    label: Page
    folder: content/pages
    create: true
    fields:
      - { name: path, label: Path, widget: string }
      - { name: title, label: Title, widget: string }
      - { name: description, label: Description, widget: text }
      - { name: body, label: Body, widget: markdown }
