backend:
  name: git-gateway
  branch: master
  repo: product-mindset/site

publish_mode: editorial_workflow  

media_folder: content/media

collections:
  - name: page
    label: Page
    folder: content/pages
    create: true
    fields:
      - { name: path, label: Path, widget: string }
      - { name: title, label: Title, widget: string }
      - { name: description, label: Description, widget: text }
      - { name: body, label: Body, widget: markdown }